toystore_ecommerce:
  outputs:
    ci:
      type: duckdb
      path: 'md:toystore_ecommerce'
      extensions:
        - motherduck
      motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: ci
      threads: 4

    prod:
      type: duckdb
      path: 'md:toystore_ecommerce'
      extensions:
        - motherduck
      motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: main
      threads: 4

  target: ci
