name: dbt CD

on:
  push:
    branches: [main]

env:
  MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
  DBT_SUBDIR: dbt_toystore_ecommerce

jobs:
  dbt-cd:
    name: dbt Deploy (Produção)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: dbt deps
        working-directory: ${{ env.DBT_SUBDIR }}
        run: dbt deps --profiles-dir .

      - name: dbt seed
        working-directory: ${{ env.DBT_SUBDIR }}
        run: dbt seed --profiles-dir . --target prod

      - name: dbt run
        working-directory: ${{ env.DBT_SUBDIR }}
        run: dbt run --profiles-dir . --target prod

      - name: dbt test
        working-directory: ${{ env.DBT_SUBDIR }}
        run: dbt test --profiles-dir . --target prod
